paceholder/nodeeditor

src/Connection.cpp
Fixed issue:
When removing a connection between nodes, only one node connector would update.
=> Fix connector drawing on connection removal

examples/calculator/AdditionModel.hpp, examples/calculator/DivisionModel.hpp, examples/calculator/MultiplicationModel.hpp, examples/calculator/NumberDisplayDataModel.hpp, examples/calculator/NumberSourceDataModel.hpp, examples/calculator/SubtractionModel.hpp, examples/calculator/main.cpp, examples/example1/main.cpp, examples/example1/models.hpp, examples/example2/TextDisplayDataModel.hpp, examples/example2/TextSourceDataModel.hpp, examples/example2/main.cpp, examples/images/ImageLoaderModel.hpp, examples/images/ImageShowModel.hpp, examples/images/main.cpp, src/DataModelRegistry.cpp, src/DataModelRegistry.hpp, src/FlowScene.cpp, src/FlowView.cpp, src/NodeDataModel.hpp
(This fixes #7)
Explanation of some less trivial changes:
in the examples' main.cpp, I moved the `registerDataModels` call to after the `QApplication` has been constructed. This is good because we are actually constructing the `NodeDataModel` instances, which means some will construct widgets, and it's illegal to construct a `QWidget` before the `QApplication` is constructed. 
Why not `make_unique`? UniquePtr.hpp is a private header, so the examples can't really use it and c++14 isn't turned on for this project (if it was turned on we could use it and not worry about UniquePtr.hpp at all)
=> Add runtime types

examples/calculator/main.cpp, examples/example1/main.cpp, examples/example2/main.cpp, examples/images/main.cpp, src/FlowScene.cpp, src/FlowScene.hpp
Use case:
You are writing an editor for graphs (like I am) and you want to have multiple graphs that share the same node types. These node types could change throughout the program execution, it would be a pain in the butt to copy them all for each update to the registry. Therefore, a shared registry is the way to go for this scenario (unless you have any other ideas)
=> Use std::shared_ptr for storing registries so editors can share them

CMakeLists.txt
This makes it so you don't have to build the examples. This is nice when building it as a library. The default behavior isn't changed.
=> Add an option to not build the examples in CMake

src/Node.cpp, src/Node.hpp, src/NodeConnectionInteraction.cpp, src/NodePainter.cpp, src/NodePainter.hpp
It's not really considered good practice to have `const unique_ptr<...>&` everywehre because you can just use C pointers that are much more flexible. The rule of thumb (at least that i've heard) is that only use smart pointers if the callee cares about the lifetime of the object. 
This actually gets rid of a potential error in `Node::nodeGraphicsObject` where somebody could change the graphics object and `recalculateSize` wouldn't be called.
=> Don't use const std::unique_ptr<...>& everywhere, use raw pointer instead

src/DataModelRegistry.hpp
This way the custom metadata that is needed for runtime defined types can be added optionally. (I need this for my uses)
=> Add the uniqueModel in DataModelRegistry::registerModel to be an optional parameter

src/FlowScene.cpp
`deleteConnection` was being called twice and `connectionCreated` not enough
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paceholder/nodeeditor/29)
=> Fix signal callbacks in FlowScene

src/Node.cpp, src/Node.hpp
It's copied out so it doesn't make sense (and it currently triggers a
warning)
=> Don't use const in reutrn type--doesn't make sense

src/Connection.cpp, src/FlowScene.cpp, src/FlowScene.hpp, src/Node.cpp
* Have the signals yield std::shared_ptr if callees want ownership
* Remove a call to updated
* Remove some resize calls that seem to be misplaced
=> Add miscalenous changes

src/Connection.cpp, src/Connection.hpp, src/ConnectionGraphicsObject.cpp, src/ConnectionGraphicsObject.hpp, src/ConnectionPainter.cpp, src/ConnectionPainter.hpp, src/ConnectionState.cpp, src/ConnectionState.hpp, src/FlowScene.cpp, src/FlowScene.hpp, src/FlowView.cpp, src/NodeConnectionInteraction.cpp, src/NodeConnectionInteraction.hpp, src/NodeGraphicsObject.cpp, src/NodeGraphicsObject.hpp, src/NodePainter.cpp, src/NodePainter.hpp, src/NodeState.cpp, src/NodeState.hpp
Nodes were stored in `shared_ptr` objects, which doesn't make sense
because `FlowScene` should be the only owner of Nodes.
=> Make Nodes uniquely owned by FlowScene instead of using shared_ptr

src/ConnectionState.hpp
The const means nothing, because the pointer is being copied anyways. This also fixes this warning:
`ConnectionState.hpp:44:9: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]`
=> Remove uneeded const

examples/calculator/DivisionModel.hpp, examples/calculator/SubtractionModel.hpp, src/NodeDataModel.hpp, src/NodeGeometry.cpp, src/NodePainter.cpp
Minor modification to add the capability to modify port labels from the node model. Helps with cases where input ports are not interchangeable, or the different ports with the same type carry different meaning. (Like the divison and subtraction nodes in the calculator example, the input ports are not interchangeable, so it's clearer to name them accordingly to what role they fill in the calculation.)
=> Renamable input and output ports on nodes

.travis.yml, examples/calculator/AdditionModel.hpp, examples/calculator/DivisionModel.hpp, examples/calculator/MathOperationDataModel.cpp, examples/calculator/MathOperationDataModel.hpp, examples/calculator/MultiplicationModel.hpp, examples/calculator/NumberDisplayDataModel.cpp, examples/calculator/NumberDisplayDataModel.hpp, examples/calculator/SubtractionModel.hpp, resources/DefaultStyle.json, src/FlowScene.cpp, src/FlowScene.hpp, src/Node.cpp, src/NodeDataModel.hpp, src/NodeGeometry.cpp, src/NodeGeometry.hpp, src/NodePainter.cpp, src/NodePainter.hpp, src/NodeStyle.cpp, src/NodeStyle.hpp
Extension to the library to provide a way to handle internal node errors in a more visible way. Nodes now have a chance to implement a kind of self validation mechanism, and report to the scene if the operation they representing is not possible on the data they contain. (Example in the calculator sample, if the division node gets a 0 value on the divisor port, that now results in a validation error.) In case of an error, the reported error message if displayed on the invalid node.
Additionally there's a minor modification to create an easy way to iterate through all the existing nodes in the scene.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/paceholder/nodeeditor/46)
=> Runtime validation and error reporting

src/FlowView.cpp
Minor addition to the node insert context menu, to make it's contents real time filterable. With a bunch of different node types, this could make the editor much easier to use.
=> Context menu filter

src/FlowScene.cpp
The CGO is requested in `NodeGraphicsObject::moveConnections` with the call stack:
```
Node::onDataUpdated
Connection::propagateData
Node::onDataUpdated
```
Which is called in createConnection
=> Fix segfault in NodeScene

examples/calculator/AdditionModel.hpp, examples/calculator/DecimalToIntegerModel.cpp, examples/calculator/DecimalToIntegerModel.hpp, examples/calculator/DivisionModel.hpp, examples/calculator/IntegerToDecimalModel.cpp, examples/calculator/IntegerToDecimalModel.hpp, examples/calculator/MathOperationDataModel.hpp, examples/calculator/ModuloModel.cpp, examples/calculator/ModuloModel.hpp, examples/calculator/MultiplicationModel.hpp, examples/calculator/NumberDisplayDataModel.hpp, examples/calculator/NumberSourceDataModel.cpp, examples/calculator/NumberSourceDataModel.hpp, examples/calculator/SubtractionModel.hpp, examples/connection_colors/models.hpp, examples/example2/TextDisplayDataModel.hpp, examples/example2/TextSourceDataModel.hpp, examples/images/ImageLoaderModel.hpp, examples/images/ImageShowModel.hpp, examples/styles/models.hpp, src/Connection.cpp, src/Connection.hpp, src/FlowScene.cpp, src/FlowScene.hpp, src/Node.cpp, src/Node.hpp, src/NodeDataModel.hpp, src/Serializable.hpp
I did not implement any sophisticated general-purpose super-duper-abstract serialization mechanism.
- Serialization is complex by itself.
- Hard to predict what would be a client's serialization system (boost? Qt's JSON? binary data?)
Thus,  there is just JSON that just works.
The output is an UTF-8 text file:
```
{
"connections": [
{
"in_id": "{3c827191-1458-48ec-9a47-2c50e640e129}",
"in_index": 0,
"out_id": "{52d330bc-9970-426e-8679-1a2bb26a8d68}",
"out_index": 0
}
],
"nodes": [
{
"id": "{3c827191-1458-48ec-9a47-2c50e640e129}",
"model": {
"name": "Result"
},
"position": {
"x": 489,
"y": 264
}
},
{
"id": "{52d330bc-9970-426e-8679-1a2bb26a8d68}",
"model": {
"name": "NumberSource",
"number": "34"
},
"position": {
"x": 135,
"y": 136
}
}
]
}
```
=> Implement Json serialization

src/FlowScene.hpp, src/NodeGraphicsObject.cpp
This allows clients (like me!) to know when nodes are moved.
=> Add node moved signal

src/FlowView.cpp
Now the user can start typing immediately.
=> Make the filter bar in the context menu have focus by default.

examples/calculator/main.cpp, src/DataModelRegistry.cpp, src/DataModelRegistry.hpp, src/FlowScene.cpp, src/FlowScene.hpp, src/FlowView.cpp
- Fixed a crash, that happened when the user tried to delete multiple selected nodes and connections
- Fixed a crash, that happened when the user tried to load a scene from file into a non-empty scene
- Added functions to FlowScene for node position manipulation, and size readback. Before this, this data were only accessible through types that are not exported from the library, but on the other hand moving nodes in code is useful for automatic graph generation. (Like generating a basic graph that the user edits, instead of giving them an empty scene.)
- Added functions to Flowscene for iterating through the existing nodes. iterateOverNodeData just iterates through the nodes, passing the node data to the visitor lambda. iterateOverNodeDataDependentOrder iterates through the nodes in a …
=> Various fixes and additions

src/make_unique.hpp
Changed the make_unique 'emulation' conditions, so that it doesn't match VS2013. (VS2013 already has make_unique in std, the standard compliance of VS versions are all over the place.)
=> Compilation fix for VS2013

.gitignore, src/FlowScene.cpp, src/FlowScene.hpp
I noticed that bug #54 was fixed in pull request #62, but the code causing it was still being used in the FlowScene destructor, so here is clearScene(), used in load() and ~FlowScene().
Also added CMakeLists.txt.user to the .gitignore
=> added clearScene()

src/FlowScene.cpp, src/FlowScene.hpp, src/NodeGraphicsObject.cpp, src/NodeGraphicsObject.hpp
I also had to add `type()` override to `NodeGraphicsObject` to allow for [qgraphicsitem_cast](http://doc.qt.io/qt-5/qgraphicsitem.html#qgraphicsitem_cast) to work
=> Add selectedNodes() function to FlowScene

src/ConnectionGraphicsObject.hpp, src/FlowView.cpp
Steps to reproduce this crash:
1. Make a graph with at least 2 nodes and 1 connection between them
2. Select a node and the connection with the marquee selection tool
3. Press delete
This fixes that crash. The problem was the connections that were to be deleted were stored, but then they were deleted when nodes were deleted, therefore they were "deleted" after they had already been deleted (double free sort of thing). This fixes it by deleting all the nodes, then all the connections.
=> Fix crash when deleting nodes in a marquee selection

src/FlowView.cpp, src/FlowView.hpp
This changes no behavior, just adds flexibility.
This allows for
1. Changing shortcuts/removing shortcuts
2. Adding these actions to a KActionCollection
3. Easily attaching them to buttons
=> Use actions in FlowView instead of built-in shortcuts

src/FlowView.cpp, src/FlowView.hpp
The code should do exactly the same thing now, just with less code.
=> Remove overriden functions that just called the base version

include/nodes/NodeGeometry, include/nodes/NodePainterDelegate, src/NodeDataModel.hpp, src/NodeGeometry.hpp, src/NodePainter.cpp, src/NodePainterDelegate.hpp
I also exposed NodeGeometry to the public API, which had to be done because it'd be hard to expose painting things without knowing where you are. 
If you have a better way to do this, I'm all ears.
I decided to go with a simple virtual function because it does basically the same thing as a delegate, but it's simpler and more concise.
=> Add onPaint callback to NodeDataModel for custom painting

src/NodeGraphicsObject.cpp
Hi,
am having a problem with a CombBox hidden behind other NodeGraphiObjects.
I realized that in general the order in Z might be annoying in some cases because is related to the creation order.
This PR proposes a solution to this problem.
NOTE: if you prefer, the increase in Zvalue can be done in **hoverEnterEvent** instead of **mousePressEvent**. I would personally prefer hoverEnterEvent.
=> fixing a problem with the Z level that affects proxywidgets too

src/ConnectionGraphicsObject.cpp, src/ConnectionGraphicsObject.hpp, src/Node.hpp, src/NodeGraphicsObject.cpp, src/NodeGraphicsObject.hpp
This PR allow the user to "lock" a node or connection, i.e. to prevent the user from moving and/or deleting it.
=> allow the ability to lock a node/connection in the editor

CMakeLists.txt, examples/calculator/DivisionModel.hpp, examples/calculator/SubtractionModel.hpp, src/ConnectionBlurEffect.cpp, src/ConnectionBlurEffect.hpp, src/FlowItemInterface.cpp, src/FlowView.cpp, src/NodeGraphicsObject.cpp, src/NodeState.cpp
We are using your project as a sub-module in CANdevStudio. As the project is build with -Wall and -Wextra flags compilation of your code produces few minor warnings - unused variables and order of initialisation. If you would like to enable these flags in your project also this PR will do it for you :-)
Signed-off-by: Remigiusz Kołłątaj <remigiusz.kollataj@mobica.com>
=> Correct -Wall and -Wextra warnings for GCC7.1.1 and Clang++ 4.0.1

CMakeLists.txt
With the current setup, if you pass `-DCMAKE_CXX_FLAGS=...` it will be ignored. This fixes that.
=> Don't ignore flags passed on the command line

src/NodeGraphicsObject.cpp
There is no possibility currently to set custom opacity. It is always set to the default one. This PR fixes the issue.
Signed-off-by: Remigiusz Kołłątaj <remigiusz.kollataj@mobica.com>
=> Opacity handling fix

src/FlowView.cpp, src/FlowView.hpp
To be able to fit this widget in the typical .ui file workflow, we need to be able to construct it with a parent widget and set the scene after UI setup.
=> Support inclusion of FlowView via Qt Designer

.appveyor.yml
The appveyor build was failing due to Qt 5.7 not being on the image we were using (https://www.appveyor.com/docs/build-environment/#qt). I specified a *build worker image* and changed the Qt version from 5.7 to 5.6.3.
=> Fix Appveyor build

.appveyor.yml, .travis.yml, CMakeLists.txt, external/CMakeLists.txt, external/Catch2/CMakeLists.txt, test/CMakeLists.txt, test/include/Stringify.hpp, test/src/TestDataModelRegistry.cpp, test/src/TestNodeGraphicsObject.cpp, test/src/test_dragging.cpp, test/test_main.cpp
* Automatically downloads Catch2 if `BUILD_TESTING` is on and Catch2 is not otherwise found.
* Fix usage of Catch2
* Use `#include <catch2/catch.hpp>` (Catch2 v2.3.0+)
* Use `Catch2::Catch2` (Catch2 v2.3.0+)
* Fix appveyor build
* MinGW can now build tests (passed [`-DCATCH_CONFIG_NO_CPP11_TO_STRING`](https://github.com/catchorg/Catch2/blob/master/docs/configuration.md#c11-toggles))
* Running the tests fail, though...
* Updated project options
* Play nicely with `add_subdirectory(nodeeditor)` workflow.
* Add a `NE_FORCE_TEST_COLOR` option which, when turned on, forces the Catch2 executable to output with color. Useful for running ctest from the commandline
* If we are the root project, set the `bin` and `lib` directories. We don't want to interfere with anyone else's …
=> Automatically get Catch2 if needed

src/ConnectionGraphicsObject.cpp
Dereferencing nullptr node causes crash on osx’s clang.
=> Fix dereferencing nullptr

include/nodes/internal/NodeGeometry.hpp, src/FlowScene.cpp, src/NodeGeometry.cpp, src/NodeState.cpp
Hi,
in my code I frequently create/remove programmatically nodes and connections.
Apparently I am doing something weird (or not) and during the cleanup some "zombie" connection still exist somewhere.
This PR will fix the symptom (crash in **Connection::save()** )  but, for the time being, not the actual illness (connection that still exist even if it was supposed to be deleted). 
In the worst case, this code is equivalent to the old one.
Davide
**P.S.**: at some point we migh start a discussion about making the code more robust using std::weak_ptr instead of raw pointers.
=> Cleaner Cleanup

include/nodes/internal/Node.hpp, include/nodes/internal/NodeDataModel.hpp, src/Node.cpp
In my application I resize the embedde widget of the NodeDataModel.
To correctly update the graphic part, I created an aditional signal/slot pair. See the video
[bt_editor_resize_node-2018-06-11_14.36.43.mkv.zip](https://github.com/paceholder/nodeeditor/files/2089948/bt_editor_resize_node-2018-06-11_14.36.43.mkv.zip)
Cheers
=> Signal that can be emitted when the size of the embedded widget changes

include/nodes/internal/NodeGeometry.hpp, src/NodeGeometry.cpp, src/NodeGraphicsObject.cpp
In my application, I want to put QTableViews as the widget in a node. Because these widgets are scrollable,the value they return from size() is not ideal for positioning them in a node. If I have several ports, then I end up with a small scrollable table floating in the middle of a large node, rather than a table which shows the maximum number of rows using up the whole vertical space. 
This change special-cases widgets which have the "QSizePolicy::ExpandFlag" set in their SizePolicy. 
* If a widget with the expand flag is smaller than the node (because there are several ports) the widget is given the entire vertical space. 
* When the widget is taller than the space required by the ports, the behaviour the same as before.
I've attached before and after screenshots. 
Without change:
With …
=> Mimimum expanding widgets

src/FlowScene.cpp
Currently, if a node topology file fails during load, the scene is cleared anyhow.
This fix only calls `clearScene()` after the file open check is performed.
=> Clearing scene only if file open doesn't fail

external/CMakeLists.txt, external/Catch2/CMakeLists.txt
The referenced versions of Catch2 were not building on Ubuntu 21.10 due to this issue: https://github.com/catchorg/Catch2/issues/2178
I've updated to the latest release.
=> Take recent catch2 to fix build issue

include/nodes/internal/FlowScene.hpp, src/FlowScene.cpp
A few months ago a change was made which meant the FlowScene::connectionCreated signal provided a const connection. Unfortunately, this meant I can't later use it to call deleteConnection, which currently expects non-const. This change makes delete connection take a const& connection.
=> Make deleteConnection take const.

src/Connection.cpp
Modify Connection's destructor so that it doesn't fire propagateEmptyData without an output node connected to it previously.
=> Adjust the behavior of Connection's destructor

include/nodes/internal/NodeDataModel.hpp
without this forward declaration it it wasn't compiling when trying to create a custom NodePainterDelegate.
=> without this forward declaration it it wasn't compiling

README.md, external/CMakeLists.txt, test/CMakeLists.txt
The original idea was to be able to include the NodeEditor library to some super-project along with the included Catch2 (also as a subprobject), i.e.:
```
add_subdirectory(catch2)
add_subdirectory(NodeEditor)
```
To do this we need to detect inside NodeEditor's CMake scripts whether the Catch2 target was already included. If not, we included our own Catch2 subdirectory.
The chosen names of the macro caused recursion when called from within vcpkg.
=> Fix redefined find_package macro for vcpkg (#328)

CMakeLists.txt, examples/calculator/CMakeLists.txt, examples/connection_colors/CMakeLists.txt, examples/example2/CMakeLists.txt, examples/images/CMakeLists.txt, examples/styles/CMakeLists.txt, test/CMakeLists.txt
This allows QtCreator and other IDEs to show header files in the source tree.
=> Add header files to CMake targets

src/DataFlowGraphicsScene.cpp
Searching through the context menu was broken after 883e8a0 due to a mis-comparison on node data that is never inserted, returning no results. This has been fixed by correctly comparing against `QTreeWidgetItem::text`.
Furthermore, the filtering system has been changed to hide empty categories, showing only those that are relevant (contain matching nodes).
Tested on Gentoo Linux, kernel 6.1.0, Qt 5.15.7
=> Fixed broken context search and hide empty categories from filter.

examples/calculator/main.cpp, include/QtNodes/internal/BasicGraphicsScene.hpp, include/QtNodes/internal/DataFlowGraphicsScene.hpp, src/BasicGraphicsScene.cpp, src/DataFlowGraphicsScene.cpp
This signal is sent when nodes or connections change.
Many editors will have a file modified flag after modifying the file. We can connect this signal to determine which scene has been modified.
=> Add a signal `modified` for the scene.

.github/workflows/cmake_build.yml, CMakeLists.txt, README.rst
https://github.com/paceholder/nodeeditor/issues/397
This seems to be intuitive option, plus adds some control for library users to use the versions they want
Added flag for switching Qt versions + readme update on this info
=> Fixed building with Qt5 and Qt6 versions installed in the same time

include/QtNodes/internal/NodeGraphicsObject.hpp, src/BasicGraphicsScene.cpp, src/NodeGraphicsObject.cpp
Currently, if a node's inputs or outputs are updated, the embedded QWidget's position will remain unchanged - possibly occluding the new ports' captions.
This code fixes that issue, and moves the embedded QWidget with the new geometry after a node has changed.
=> [Bug Fix] Update embedded QWidget position after node update

include/QtNodes/internal/AbstractNodeGeometry.hpp, include/QtNodes/internal/DefaultHorizontalNodeGeometry.hpp, include/QtNodes/internal/DefaultVerticalNodeGeometry.hpp, src/AbstractNodeGeometry.cpp, src/DefaultHorizontalNodeGeometry.cpp, src/DefaultVerticalNodeGeometry.cpp
The current ratio-based calculation for bounding rectangle leads to a weird situation where the mouse does not necessarily select the nearest node. In the screenshot, the mouse is selecting the top node rather than the nearer node on the left:
This PR fixes the problem using a fixed value (twice the port spacing) as the extra margin. Since the required information is not available in the AbstractNodeGeometry, the boundingRect method has been made pure virtual and implementations are provided in DefaultHorizontalNodeGeometry and DefaultVerticalNodeGeometry.
=> Use a fixed margin for bounding rectangle rather than a ratio of node size

include/QtNodes/internal/BasicGraphicsScene.hpp, src/BasicGraphicsScene.cpp
The context is some drag and drop code which needs to know when a drag operation from the widget inside a node has left the node. My calculations need access to the node geometry.
(Additional context: I'm transitioning some working code from nodeeditor v2 to v3.)
=> Provide a const BasicGraphicsScene::nodeGeometry method

docs/features.rst, examples/styles/main.cpp, include/QtNodes/internal/NodeStyle.hpp, resources/DefaultStyle.json, src/NodeGraphicsObject.cpp, src/NodeStyle.cpp
In my app if count nodes more 30+, so then starting freezing and downing performance. The culprit of all this's shadows. I added enabler shadow. And now in my project disabled shadows and i can spawn very more nodes
There was a problem:
=> Optimizing performance | Add shadow enabler

examples/lock_nodes_and_connections/main.cpp, include/QtNodes/internal/UndoCommands.hpp
Build failures were occurring because the headers referenced in the changeset are at different locations in Qt5 and Qt6.
=> fix: includes are not compatible with Qt5

include/QtNodes/internal/AbstractGraphModel.hpp, include/QtNodes/internal/DataFlowGraphModel.hpp, include/QtNodes/internal/NodeConnectionInteraction.hpp, src/DataFlowGraphModel.cpp, src/NodeConnectionInteraction.cpp, test/include/TestDataFlowNodes.hpp, test/src/TestDataFlow.cpp, test/src/TestDataFlowGraphModel.cpp
First commits brings test-classes implementation to the definition of these classes in the header for simplicity.
Second commit:
- extends unit-tests that tries to make a loop
- implemetns depth-first search to detect a recursion in DataFlowGraphModel::connectionPossible
=> Control loops before connecting depending on AbstractGraphModel::loopsEnabled() 
